import {
	banner1,
	banner1_1024,
	banner1_1200,
	banner1_768,
	banner2,
	banner2_1024,
	banner2_1200,
	banner2_768,
	bannerAboutUs,
	blog1,
	blog2,
	blog3,
	category1,
	category2,
	category3,
	category4,
	category5,
	category6,
	product10_1,
	product10_2,
	product1_1,
	product1_2,
	product2_1,
	product2_2,
	product3_1,
	product3_2,
	product4_1,
	product4_2,
	product5_1,
	product5_2,
	product6_1,
	product6_2,
	product7_1,
	product7_2,
	product8_1,
	product8_2,
	product9_1,
	product9_2,
	salesBanner1,
	salesBanner2,
	shipping1,
	shipping2,
	shipping3,
	whychoose1,
	whychoose2,
	whychoose3,
} from "../utils/helper";

export const categoryItems = [
	{
		id: 1,
		title: "Sofa",
		imgSrc: category1,
	},
	{
		id: 2,
		title: "Lighting",
		imgSrc: category2,
	},
	{
		id: 3,
		title: "Bathroom",
		imgSrc: category3,
	},
	{
		id: 4,
		title: "Bedrooom",
		imgSrc: category4,
	},
	{
		id: 5,
		title: "Outdoor",
		imgSrc: category5,
	},
	{
		id: 6,
		title: "Home Kitchen",
		imgSrc: category6,
	},
];

export const salesItems = [
	{
		id: 1,
		link: "#!",
		imgSrc: salesBanner1,
		title: "Top Trend Style",
		superHeading: "SALE 50% OFF",
		description: "In-store & online. HUrry up! Limited time offer.",
	},
	{
		id: 2,
		link: "#!",
		imgSrc: salesBanner2,
		title: "Here's to You",
		superHeading: "Hot Under $59",
		description: "Discover selected items with many discounts.",
	},
];

export const shippingItems = [
	{
		id: 1,
		imgSrc: shipping1,
		title: "Free Shipping",
		description: `Get complimentary ground shipping on every order. Don't love it? Send it back, on us.`,
	},
	{
		id: 2,
		imgSrc: shipping2,
		title: "Free Returns",
		description: `Free returns within 10 days, please make sure the items are in undamaged condition.`,
	},
	{
		id: 3,
		imgSrc: shipping3,
		title: "Support Online",
		description: `We support customers 24/7, send questions we will solve for you immediately.`,
	},
];

export const blogItems = [
	{
		id: 1,
		imgSrc: blog1,
		date: "Apr 28 2023",
		author: "Ruston Grey",
		category: "FURNITURE",
		title: "Restoring Old Furniture Pieces",
		description: `These are the people who make your life asier. Large tiles were arranged on the counter top plate near the window of the living room, they...`,
	},
	{
		id: 2,
		imgSrc: blog2,
		date: "May 21 2023",
		author: "Sasha Brown",
		category: "FURNITURE",
		title: "Eco-friendly Furniture For Home",
		description: `These are the people who make your life asier. Large tiles were arranged on the counter top plate near the window of the living room, they...`,
	},
	{
		id: 3,
		imgSrc: blog3,
		date: "Jun 18 2023",
		author: "John Marvel",
		category: "FURNITURE",
		title: "Investing In High-quality Furniture",
		description: `These are the people who make your life asier. Large tiles were arranged on the counter top plate near the window of the living room, they...`,
	},
];

export const bannerItems = [
	{
		id: 1,
		imgSrc: banner1,
		imgSrc768: banner1_768,
		imgSrc1024: banner1_1024,
		imgSrc1200: banner1_1200,
		title: "Bedroom Textiles",
		superHeading: "Beautiful & Elegant",
		subHeading: "Discount 50% on Products & Free Shipping.",
	},
	{
		id: 2,
		imgSrc: banner2,
		imgSrc768: banner2_768,
		imgSrc1024: banner2_1024,
		imgSrc1200: banner2_1200,
		title: "Pendant Light",
		superHeading: "Kitchen Tools ",
		subHeading: "Discount 50% on Products & Free Shipping.",
	},
];

export const pageBannerItems = [
	{
		id: 1,
		imgSrc: bannerAboutUs,
		title: "Our Perfect Store",
		superHeading: "WELCOME TO UMINO",
		description: `Over 20 years of experience, we have crafted thousands of strategic discovery process that enables us to peel back the layers which enable us to understand, connect understand, connect.`,
	},
];

export const whyChooseItems = [
	{
		id: 1,
		imgSrc: whychoose1,
		title: "Unique for Women’s",
		description: `Our collections dress a unique and feminine woman. The pieces showcase a timeless style while keeping in mind fashion aesthetics and trends.`,
	},
	{
		id: 2,
		imgSrc: whychoose2,
		title: "Elegant for Men’s",
		description: `From traditional tailoring to the most informal pieces. Our Umino Man collections feature the latest trends with the maximum comfort.`,
	},
	{
		id: 3,
		imgSrc: whychoose3,
		title: "Freedom for Everyone",
		description: `The designs have been created adopting the current trends, while leaving room for personal expression among young people.`,
	},
];

export const productItems = [
	{
		id: 1,
		stars: 0,
		price: 280.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product1_1,
		imgSrc11: product1_2,
		title: "Form Chair Brass Base",
		category: ["Sofa", "Outdoor", "Bathroom"],
	},
	{
		id: 2,
		stars: 5,
		price: 80.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product2_1,
		imgSrc11: product2_2,
		title: "Vase Echasse Large",
		category: ["Outdoor", "Home Kitchen", "Bedroom"],
	},
	{
		id: 3,
		stars: 1,
		price: 150.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product3_1,
		imgSrc11: product3_2,
		title: "Simple Model Chair",
		category: ["Sofa", "Outdoor"],
	},
	{
		id: 4,
		stars: 4,
		price: 120.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product4_1,
		imgSrc11: product4_2,
		title: "Bottle Grinder of Pepper",
		category: ["Home Kitchen", "Bathroom"],
	},
	{
		id: 5,
		stars: 4,
		price: 120.0,
		cartQuantity: 1,
		priceCrossed: 130.0,
		imgSrc1: product5_1,
		imgSrc11: product5_2,
		title: "Form Bar Stool Oak Base",
		category: ["Sofa", "Outdoor"],
	},
	{
		id: 6,
		stars: 3,
		price: 160.0,
		cartQuantity: 1,
		priceCrossed: 200.0,
		imgSrc1: product6_1,
		imgSrc11: product6_2,
		title: "Carrie Table Lamp",
		category: ["Outdoor", "Lighting", "Bedroom", "Home Kitchen"],
	},
	{
		id: 7,
		stars: 5,
		price: 60.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product7_1,
		imgSrc11: product7_2,
		title: "Wooden Lamp Drop",
		category: ["Outdoor", "Lighting", "Bedroom", "Home Kitchen"],
	},
	{
		id: 8,
		stars: 4,
		price: 60.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product8_1,
		imgSrc11: product8_2,
		title: "Hammershoi Spice Mill Small",
		category: ["Home Kitchen", "Bathroom"],
	},
	{
		id: 9,
		stars: 5,
		price: 300.0,
		cartQuantity: 1,
		priceCrossed: "",
		imgSrc1: product9_1,
		imgSrc11: product9_2,
		title: "Wave Sideboard Anthracite",
		category: ["Outdoor", "Home Kitchen"],
	},
	{
		id: 10,
		stars: 4,
		price: 160.0,
		cartQuantity: 1,
		priceCrossed: 200.0,
		imgSrc1: product10_1,
		imgSrc11: product10_2,
		title: "Form Armchair Black",
		category: ["Sofa", "Outdoor", "Bedroom"],
	},
];

export const contactAddressItems = [
	{
		id: 1,
		tel: "+222-1800-262",
		branch: "Umino - United States",
		hours: "Everyday 9:00 am - 6:00 pm",
		address: "68 St, South New York/NY 98944, United States. blueskytechcompany@gmail.comm",
	},
	{
		id: 2,
		tel: "+222-1800-262",
		branch: "Umino - India",
		hours: "Everyday 9:00 am - 6:00 pm",
		address: "68 St, South New York/NY 98944, United States. blueskytechcompany@gmail.comm",
	},
	{
		id: 3,
		tel: "+222-1800-262",
		branch: "Umino - United Kingdom",
		hours: "Everyday 9:00 am - 6:00 pm",
		address: "68 St, South New York/NY 98944, United States. blueskytechcompany@gmail.comm",
	},
];
